version: '3.8'
services:
  back_dz:
    environment:
      PHP_XDEBUG_DEFAULT_ENABLE: ${PHP_XDEBUG_DEFAULT_ENABLE}
      PHP_XDEBUG_REMOTE_ENABLE: ${PHP_XDEBUG_REMOTE_ENABLE}
      PHP_XDEBUG_REMOTE_HOST: ${PHP_XDEBUG_REMOTE_HOST}
      PHP_XDEBUG_REMOTE_PORT: ${PHP_XDEBUG_REMOTE_PORT}
      PHP_XDEBUG_REMOTE_AUTO_START: ${PHP_XDEBUG_REMOTE_AUTO_START}
      PHP_XDEBUG_REMOTE_CONNECT_BACK: ${PHP_XDEBUG_REMOTE_CONNECT_BACK}
      PHP_XDEBUG_IDEKEY: ${PHP_XDEBUG_IDEKEY}
      PHP_XDEBUG_PROFILER_ENABLE: ${PHP_XDEBUG_PROFILER_ENABLE}
      PHP_XDEBUG_PROFILER_OUTPUT_DIR: ${PHP_XDEBUG_PROFILER_OUTPUT_DIR}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
volumes:
  back_dz:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/back
      o: bind
  
