version: '3.8'

services:
  consumer:
    image: php:7.4-fpm-alpine
    volumes:
      - back:/var/www/html/back
    environment:
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
      NO_PROXY: ${NO_PROXY}
      SYMFONY_ENV: ${SYMFONY_ENV}
      BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - 8087:82
volumes:
  back:

networks:
  docker.dc:
    name: dz