#!/bin/sh

set -e

if [ -n "$HOST_GID" ]; then 
  echo "SET www-data group ID: $HOST_GID";
  sed -i 's/\(www-data:x\):\(.\d\):\(.*\)$/\1:'${HOST_GID}':\3/g' /etc/group
else
  HOST_GID=$(id www-data)
fi

if [ -n "$HOST_UID" ]; then 
  echo "SET www-data user ID: $HOST_UID";
  sed -i 's/\(www-data:x\):\(.\d\):\(.\d\):\(.*\)$/\1:'${HOST_UID}':'${HOST_GID}':\4/g' /etc/passwd
  rm -rf /etc/{passwd,group}-
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

if [ -d "/entrypoint.d" ]; then    
    for ep in /entrypoint.d/*.sh; do
      if [ ! -x "${ep}" ]; then
         chmod +x "${ep}"
      fi
      echo "Running: ${ep}"
      /bin/sh "${ep}"
    done
fi

chown -R www-data:www-data /var/www/html;

exec "$@"
